# core/job.py
# The Job dataclass — atomic unit of work for the content pipeline.

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
import uuid


@dataclass
class ContentJob:
    """
    One job = one school event = one pipeline run.
    Construct this and pass it to run.py — everything else is automated.
    """

    # Who and what
    school_id:       str                  # must match a file in configs/
    description:     str                  # natural language brief you write, e.g.
                                          # "Sports Day held Monday 20 June 2025.
                                          #  20 raw photos attached. Make a recap
                                          #  carousel and an announcement story."

    # Media
    raw_media_dir:   str                  # path to folder with input photos/videos

    # What to produce — "auto" lets the content agent decide
    post_types:      list[str] = field(default_factory=lambda: ["auto"])
    # Which platform variants to render — "all" renders every variant in the schema
    variants:        list[str] = field(default_factory=lambda: ["all"])

    # Auto-filled
    job_id:          str = field(default_factory=lambda: datetime.now().strftime("%Y%m%d_%H%M%S") + "_" + uuid.uuid4().hex[:6])
    created_at:      str = field(default_factory=lambda: datetime.now().isoformat())
    output_dir:      Optional[str] = None  # auto-set by run.py if None


@dataclass
class RenderTask:
    """
    One render task = one template variant = one PNG output.
    Generated by the content agent, consumed by the render pipeline.
    """
    template_id:     str           # e.g. "event_recap"
    variant:         str           # e.g. "instagram_square"
    filled_fields:   dict          # what the AI filled in — merged with school config at render time
    slide_index:     int = 0       # for carousels — which slide number
    is_carousel:     bool = False  # if True, render_agent loops over slides data
    slides_data:     list  = field(default_factory=list)  # list of filled_fields per slide